apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB7k/TLS9EsietIUwtFIPzQ4APDhsSKcKVVF07DuYrRjkbW9aHK47QOZ0B3Bk1zC+Eap20qhAV+w+AhjF42SjVxqUgI4oQO11UHEfa28cAsgYTiHdoatV+GbN3yVjTJcmDzUnSFemT0N/sGWXYjBN2k2gZyMnpEQ9Y/aZ+GKTMyaYcxR/u4hniK4dfAKQHDfLraoQXd3CDwoSLvECrmRNIIUIMrTamtD/RjUA6ABQ6YB3jxnZsKW5ncchxUK6O8Wri3N+W0FdSobfSqjq+nmxiULEdVgAn/HpAhUE+HJaCc2WaWcZQ9aFL4n1KH60DQ3T7ataOcVaRV6uA+2HwKMUJ4ziZBikp5f5M7YiuClAXEKsPWiDTFZTP8PN8KqhjblxRtk9zS4yeeOEgqyljKugjfam23o3XpuRx4e+tuLFmInMy5dKXmyj36btJzxIrhkNle6lPhQPRm03/2j+OOqDZddnsVF0eupMt8dgtOM+PDuzWqratVTF2jnSSV00Wxy0Wok9vQsxyCkmHGPvkYjNNXa8Iz+z0OPWn3wIGFIXCDWXJO4WXRd15aX7R0zga/U3kOM12eCC4yHuxc9v8cJIXv0pPGfw0gY1xVsggmJy0hvu7qycXp/1Q6Kbx7/PxQj7Osr1kaGLX2BsZcy4qVklDGc8aYVlVqYLLn/jHPOxPlBiETxLw9qx2j2bEUae5ENn5NDGJZx7blJOONaL5VBwyS7OU+bw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
