apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCqJcfg3ehJPx7NJDM/2kMipCpoyPVCM7Zjn8HWE1X6jS3yxofx8kYjC96KTLoSg9h9XEZnrKr8nSrnQHTYHFyR/W83hKzz18aqbbGSTEJZo0xJdkWICciP6vFVxfHKvrDRiX83ISZvxHwMkE9ojez++FU2gbweklWglVSgPRODBaKDS1f00p2uVwLHneCvmQy7JF5OoPqgG8pnckB0sHyuSOscclxS5pmLbUW/TCt8zTk7zBizVPwakunhCdu93aJWPAWWSRKjjSqmp67WZD4zuCEq9VZCxwmvWyePQVVUnVKtKPyU0Q9m4Kyj3AAXG6Ugxcv+GdtS/2Q9Nj1047xNZT32XtOc6hUBgpXikDSNDJNoQpBtwsNWfIm7ZQs8BGs9Eyw8vqK6garPcmYXD5/DlDqB/1g23qPEpQwnpFgGc+WJOsUPXM8JRN6H9E5Z4+T7/asxMJZSDaZb2nzlOId6C9hzfpLDN9XwT+XIV1yleFTI7hs7oLODJqqBQpJjrWaJJtugQTdXjwlQp3KIdzOIh8jIusEvSU3vhXrvjsmlm85kiVTe9HOf+IHKBrByjq1+j6TJPn2/eXWAdlUTz1l/lskBss6aSaGm8joe4Zuz108aypuM5UuGSXXAh0DPrspEQEB1wK7cypXKYgs4XuyCk/tiTbfrMiQHlkFsuDHW0ZjhEhLemsMG9grnGwExL3uu3mo4FPe5PkvovrMMptNg1Qwdbg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
